# Dragon Real EstatePrice Predictor

In [1]:
import pandas as pd

In [2]:
housing = pd.read_csv("data.csv")

In [3]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [4]:
housing = pd.read_csv("data.csv")

In [5]:
housing.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [6]:
housing.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       501 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB


In [7]:
housing["CHAS"].value_counts()

0    471
1     35
Name: CHAS, dtype: int64

In [8]:
housing.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  501.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.286407   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.704732   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885000   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.209000   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.625000   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT        MEDV  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [9]:
# to plot histogram
#%matplotlib inline
#import matplotlib.pyplot as plt
#housing.hist(bins=50,figsize=(20,15))

# Train-Test Splitting

In [10]:
# implementation of train and test data
#import numpy as np
#def split_train_test(data,test_ratio):
#    np.random.seed(42)
#    shuffled =np.random.permutation(len(data))
#    print(shuffled)
#    test_set_size=int(len(data)*test_ratio)
#    test_indices= shuffled[:test_set_size]
#    train_indices=shuffled[test_set_size:]
#    return data.iloc[train_indices],data.iloc[test_indices]

#print(f"Rows in train set: {len(train_set)}\nRows in test set: {len(test_set)}\n")
#train_set,test_set=split_train_test(housing,0.2)

In [11]:
# split_train_test function from scikit learn
from sklearn.model_selection import train_test_split
train_set,test_set = train_test_split(housing,test_size=0.2,random_state=42)
print(f"Rows in train set: {len(train_set)}\nRows in test set: {len(test_set)}\n")

Rows in train set: 404
Rows in test set: 102



In [12]:
from sklearn.model_selection import StratifiedShuffleSplit
split= StratifiedShuffleSplit(n_splits=1,test_size=0.2,random_state=42)
for train_index,test_index in split.split(housing,housing["CHAS"]):
    strat_train_set=housing.loc[train_index]
    strat_test_set=housing.loc[test_index]

In [13]:
strat_test_set

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS  RAD  TAX  \
342   0.02498   0.0   1.89     0  0.518  6.540   59.7  6.2669    1  422   
379  17.86670   0.0  18.10     0  0.671  6.223  100.0  1.3861   24  666   
223   0.61470   0.0   6.20     0  0.507  6.618   80.8  3.2721    8  307   
219   0.11425   0.0  13.89     1  0.550  6.373   92.4  3.3633    5  276   
48    0.25387   0.0   6.91     0  0.448  5.399   95.3  5.8700    3  233   
..        ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
88    0.05660   0.0   3.41     0  0.489  7.007   86.3  3.4217    2  270   
466   3.77498   0.0  18.10     0  0.655  5.952   84.7  2.8715   24  666   
52    0.05360  21.0   5.64     0  0.439  6.511   21.1  6.8147    4  243   
121   0.07165   0.0  25.65     0  0.581  6.004   84.1  2.1974    2  188   
218   0.11069   0.0  13.89     1  0.550  5.951   93.8  2.8893    5  276   

     PTRATIO       B  LSTAT  MEDV  
342     15.9  389.96   8.65  16.5  
379     20.2  393.74  21.78  10.2  
223     17.4  396.90   7.60  30.1  
219     16.4  393.74  10.50  23.0  
48      17.9  396.90  30.81  14.4  
..       ...     ...    ...   ...  
88      17.8  396.90   5.50  23.6  
466     20.2   22.01  17.15  19.0  
52      16.8  396.90   5.28  25.0  
121     19.1  377.67  14.27  20.3  
218     16.4  396.90  17.92  21.5  

[102 rows x 14 columns]

In [14]:
strat_test_set.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 102 entries, 342 to 218
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     102 non-null    float64
 1   ZN       102 non-null    float64
 2   INDUS    102 non-null    float64
 3   CHAS     102 non-null    int64  
 4   NOX      102 non-null    float64
 5   RM       101 non-null    float64
 6   AGE      102 non-null    float64
 7   DIS      102 non-null    float64
 8   RAD      102 non-null    int64  
 9   TAX      102 non-null    int64  
 10  PTRATIO  102 non-null    float64
 11  B        102 non-null    float64
 12  LSTAT    102 non-null    float64
 13  MEDV     102 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 12.0 KB


In [15]:
strat_test_set["CHAS"].value_counts()

0    95
1     7
Name: CHAS, dtype: int64

In [16]:
strat_train_set["CHAS"].value_counts()

0    376
1     28
Name: CHAS, dtype: int64

In [17]:
376/28

13.428571428571429

In [18]:
 95/7

13.571428571428571

In [19]:
housing=strat_train_set.copy()

# Looking for correation matrix

In [20]:
corr_matrix= housing.corr()

In [21]:
corr_matrix["MEDV"].sort_values(ascending=False)

MEDV       1.000000
RM         0.680163
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [22]:
#from pandas.plotting import scatter_matrix
#attributes =["MEDV","RM","ZN","LSTAT"]
#scatter_matrix(housing[attributes],figsize=(12,8))

In [23]:
#housing.plot(kind="scatter",x="RM", y="MEDV", alpha=0.8)

# TRYING  OUT ATTRIBUTE COMBINATION

In [24]:
housing["TAXRM"]=housing["TAX"]/housing["RM"]

In [25]:
corr_matrix= housing.corr()

In [26]:
corr_matrix["MEDV"].sort_values(ascending=False)

MEDV       1.000000
RM         0.680163
B          0.361761
ZN         0.339741
DIS        0.240451
CHAS       0.205066
AGE       -0.364596
RAD       -0.374693
CRIM      -0.393715
NOX       -0.422873
TAX       -0.456657
INDUS     -0.473516
PTRATIO   -0.493534
TAXRM     -0.524444
LSTAT     -0.740494
Name: MEDV, dtype: float64

In [27]:
#housing.plot(kind="scatter",x="TAXRM", y="MEDV", alpha=0.8)

In [28]:
housing = strat_train_set.drop('MEDV',axis=1)
housing_labels = strat_train_set["MEDV"].copy()


# MISSING ATTRIBUTES

In [29]:
#To take care of missing attributes, you have three options:
#     1. GET RID OF THE MISSSING DATA POINTS
#     2. GET RID OF WHOLE ATTRIBUTES
#     3. SET THE VALUE TO SAME VALUE (0, mean or median)

In [30]:
#a=housing.dropna(subset=["RM"]) #OPTION 1
#a.shape
#note rows where attributes were missing are dropped

In [31]:
#housing.drop("RM", axis =1).shape #option 2
#note that there is no RM column

In [32]:
#median=housing["RM"].median()#option 3 median is filled in empty cells
#housing["RM"].fillna(median)

In [33]:
# origianal data will remaoin unchanged
housing.shape

(404, 13)

In [34]:
housing.describe() #before we started filling missing attribute

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  400.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.281365   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.714987   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.878750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.210000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.632000   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [35]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(strategy="median")
imputer.fit(housing)

SimpleImputer(strategy='median')

In [36]:
imputer.statistics_

array([2.86735e-01, 0.00000e+00, 9.90000e+00, 0.00000e+00, 5.38000e-01,
       6.21000e+00, 7.82000e+01, 3.12220e+00, 5.00000e+00, 3.37000e+02,
       1.90000e+01, 3.90955e+02, 1.15700e+01])

In [37]:
X= imputer.transform(housing)

In [38]:
housing_tr = pd.DataFrame(X,columns=housing.columns)

In [39]:
housing_tr.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean     3.602814   10.836634   11.344950    0.069307    0.558064    6.280658   
std      8.099383   22.150636    6.877817    0.254290    0.116875    0.711465   
min      0.006320    0.000000    0.740000    0.000000    0.389000    3.561000   
25%      0.086962    0.000000    5.190000    0.000000    0.453000    5.879750   
50%      0.286735    0.000000    9.900000    0.000000    0.538000    6.210000   
75%      3.731923   12.500000   18.100000    0.000000    0.631000    6.630250   
max     73.534100  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  404.000000  404.000000  404.000000  404.000000  404.000000  404.000000   
mean    69.039851    3.746210    9.735149  412.341584   18.473267  353.392822   
std     28.258248    2.099057    8.731259  168.672623    2.129243   96.069235   
min      2.900000    1.129600    1.000000  187.000000   13.000000    0.320000   
25%     44.850000    2.035975    4.000000  284.000000   17.400000  374.617500   
50%     78.200000    3.122200    5.000000  337.000000   19.000000  390.955000   
75%     94.100000    5.100400   24.000000  666.000000   20.200000  395.630000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT  
count  404.000000  
mean    12.791609  
std      7.235740  
min      1.730000  
25%      6.847500  
50%     11.570000  
75%     17.102500  
max     36.980000

In [40]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
my_pipeline =Pipeline([('imputer',SimpleImputer(strategy="median")),('std_scaler',StandardScaler()),])

In [41]:
housing_num_tr= my_pipeline.fit_transform(housing)

In [42]:
housing_num_tr.shape

(404, 13)

# Selecting a desired model for dragon real estate

In [43]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
#model=LinearRegression()
#model = DecisionTreeRegressor()
model=RandomForestRegressor()
model.fit(housing_num_tr,housing_labels)

RandomForestRegressor()

In [44]:
some_data= housing.iloc[:5]

In [45]:
some_labels= housing_labels.iloc[:5]

In [46]:
prepared_data=my_pipeline.transform(some_data)

In [47]:
model.predict(prepared_data)

array([22.307, 25.806, 16.24 , 23.395, 23.536])

In [48]:
list(some_labels)

[21.9, 24.5, 16.7, 23.1, 23.0]

# lets evaluate the model

In [49]:
from sklearn.metrics import mean_squared_error
import numpy as np
housing_predictions = model.predict(housing_num_tr)
lin_mse=mean_squared_error(housing_labels,housing_predictions)
lin_rmse= np.sqrt(lin_mse)

In [50]:
lin_rmse

1.1953439570862328

# Using better evaluattion technique -Cross validation

In [51]:
from sklearn.model_selection import cross_val_score
scores= cross_val_score(model,housing_num_tr,housing_labels,scoring="neg_mean_squared_error",cv=10)
rmse_scores=np.sqrt(-scores)

In [52]:
rmse_scores

array([2.83620811, 2.9097308 , 4.23013057, 2.58806181, 3.45260379,
       2.62974337, 4.6334025 , 3.3406612 , 3.57485501, 3.48128725])

In [53]:
def print_scores(scores):
    print("Scores: ",scores)
    print("Mean",scores.mean())
    print("Standard deviation: ",scores.std())

In [54]:
print_scores(rmse_scores)

Scores:  [2.83620811 2.9097308  4.23013057 2.58806181 3.45260379 2.62974337
 4.6334025  3.3406612  3.57485501 3.48128725]
Mean 3.367668440961596
Standard deviation:  0.6367243857891762


# Saving the model

In [55]:
from joblib import dump,load
dump(model,"Real Estates")

['Real Estates']

# Testing the model

In [56]:
X_test = strat_test_set.drop("MEDV",axis=1)
Y_test = strat_test_set["MEDV"].copy()
X_test_prepared = my_pipeline.transform(X_test)
final_predictions= model.predict(X_test_prepared)
final_mse= mean_squared_error(Y_test,final_predictions)
final_rmse=np.sqrt(final_mse)
#print(final_predictions,"\n\n",list(Y_test))

In [57]:
final_rmse

3.009860784351407

# Using the model

In [58]:
from joblib import dump,load
import numpy as np
model=load("Real Estates.joblib")
features = np.array([[-0.43942006,  3.12628155, -1.12165014, -0.27288841, -1.42262747,
       -0.24298109, -1.31238772,  2.61111401, -1.0016859 , -0.5778192 ,
       -0.97491834,  0.41164221, -0.86091034]])
x=my_pipeline.transform(features)
model.predict(x)

array([28.099])